### ISSUE TITLE
ansi-color-regexp doesn't exists in latest emacs code

### ISSUE THREAD

**Issue by diego-alvarez-hs** [hvesalai/emacs-sbt-mode#115]
`ansi-color-regexp` was dropped in this PR:
https://github.com/emacs-mirror/emacs/commit/35ed01dfb3f811a997e26d843e9971eb6b81b125

**Comment by fommil** [comment]
interesting. This should probably be fixed along with #100 which has been driving me *crazy* these last few weeks because my team is using a different scalatest spec than I'm used to and none of the extractors are working.

**Comment by fommil** [comment]
in fact, let's merge the tickets

**Comment by fommil** [comment]
reopening because this is a different issue. Perhaps we can just remove the regexp now? // @VlachJosef

**Comment by VlachJosef** [comment]
I'll test hydra with ansi-color support, maybe it will be ok to drop it.
