### ISSUE TITLE
ansi colors partly broken

### ISSUE THREAD

**Issue by Pitometsu** [hvesalai/emacs-sbt-mode#150]
![screenshot from 2018-06-11 17-08-37](https://user-images.githubusercontent.com/2434691/41236606-37274902-6d9a-11e8-9e67-b7d4b19a7298.png)

**Comment by muld3r** [comment]
I'm having the same issue. 

I think it's related to some 'latency/parsing order', as for me this ansi-color error occurs about 70% of the time, if the same sbt ouput is issued several times repeatedly.

Though I'm not using stock emacs. Problem occurs with:
+ spacemacs 3.0.0 (DEV)
+ sbt 1.1.6 + scala 2.12.6 + latest ensime/sbt-mode from melpa as of today

Can you give me a hint where to start debugging?

**Comment by hvesalai** [comment]
Is this still a problem. Not seeing it on emacs 27

**Comment by hvesalai** [comment]
I'll close this. Please open if you see it on a recent version of emacs
