### ISSUE TITLE
SBT 1.3.0 not supported; is this project dead?

### ISSUE THREAD

**Issue by markschaake** [hvesalai/emacs-sbt-mode#152]
I know that ensime is no longer maintained and that the [metals](https://scalameta.org/metals) is now the recommended replacement.  However, the [metals documentation for emacs](https://scalameta.org/metals/docs/editors/emacs.html) has an example emacs config that adds `sbt-mode`:

```elisp
(use-package sbt-mode
  :commands sbt-start sbt-command
  :config
  ;; WORKAROUND: https://github.com/ensime/emacs-sbt-mode/issues/31
  ;; allows using SPACE when in the minibuffer
  (substitute-key-definition
   'minibuffer-complete-word
   'self-insert-command
   minibuffer-local-completion-map))
```

Prior to SBT 1.3.0, I have been successfully using metals + `sbt-mode` and have felt it has been a decent replacement for my previous ensime experience (which was great).  However, SBT 1.3.0's new console output has broken some of `sbt-mode`, notably tab completion.  Even if you turn off the "super shell" tab completion still does not work.

I'm wondering:

- Is it correct to assume that this `sbt-mode` repository is no longer maintained?  
- If so, does anyone know of a maintained replacement option?

I might be interested in trying to maintain a fork, but I am not much of an elisper.

**Comment by bjarkevad** [comment]
Tab completion seems to work in Spacemacs with super shell disabled (I added `-Dsbt.supershell=false` to `sbt:program-options`).

**Comment by markschaake** [comment]
@bjarkevad that works for me too (not a spacemacs user).  I just customized the `sbt:program-options` using `customize`.  Thanks for the tip!

**Comment by rossabaker** [comment]
I can't imagine wanting supershell in sbt-mode. I think we should add that to the defaults.

**Comment by hvesalai** [comment]
Yes, I made all the tab-completion changes to SBT 1.3.0 my self way back, so my intention was that 1.3.0 is supported by sbt-mode. However, since I'm still my self stuck in an older SBT, I haven't yet had the time to actually test it.

If any of you have time to change sbt-mode so that it better supprot 1.3.0, a PR is always welcomed.

And as for the question whether this project is dead, the answer is no. As the original author, I'm still using it my self daily.

**Comment by hvesalai** [comment]
I'm closing this as I have no problems with latest SBT
