### ISSUE TITLE
Kill sbt command without killing the process

### ISSUE THREAD

**Issue by alexanderjamesking** [hvesalai/emacs-sbt-mode#157]
First of all, many thanks for your work, it is much appreciated!

If I run `sbt-start`, and then run a command e.g. `run` or `~compile` then I don't seem to be able to stop the `run` command without killing the process and the buffer, but then I have to run `sbt-start` again which isn't ideal.

I was expecting `C-c C-c` to do the trick but that's not working for me.

Edit: I just noticed https://github.com/hvesalai/emacs-sbt-mode#triggered-execution and `C-c C-j` gets me out of `~compile` but not `run` which results in `"Text is read-only"`.

I'm running sbt `1.3.10` which could be related?

**Comment by hvesalai** [comment]
@VlachJosef thank you!

@alexanderjamesking maybe you would like to do a PR that adds a section in the documentation about this?

**Comment by alexanderjamesking** [comment]
Thanks for the quick replies, `C-c C-d` didn't work for me, but I did get it working by changing `comint-prompt-read-only` from `t` to `nil` in https://github.com/hvesalai/emacs-sbt-mode/blob/master/sbt-mode-comint.el#L84

I'm not sure if there is a knock on effect of this change yet, I'll be using it today so I'll see if I get any unexpected behaviour, and if all is well then I'll can a PR unless there is a good reason for it being set to read only?

I'm happy to contribute to this project once I get a bit more familiar with using it. I've been extending it a bit locally in order to run a test at a point, or all tests for a file etc.

**Comment by VlachJosef** [comment]
Hmmm, `C-c C-d` doesn't work for me either when using `~run`. I guess that's the reason why I don't use `~` commands. I'm using `before-save-hook` to check if some scala file has been modified and if yes, then sbt-mode will run last command again. This avoids need for `~`.

**Comment by hvesalai** [comment]
`C-c C-c` works for me
