### ISSUE TITLE
Questiion: would it make sense to add commands for running single test cases to sbt-mode?

### ISSUE THREAD

**Issue by ag91** [hvesalai/emacs-sbt-mode#159]
Hi,
Thanks for this mode, speeds up my Scala development!
I just published a [blog](https://ag91.github.io/blog/2020/10/23/run-a-single-scalatest-case-with-emacs-and-sbt-mode/) in which I explain how to extend sbt-mode to run a single test class or test file.
Should I submit the code as a PR for this repository, or is this outside of the scope of this repository?

Thanks again!

**Comment by VlachJosef** [comment]
@ag91 There is already similar functionality implemented in https://github.com/hvesalai/emacs-sbt-mode/blob/master/sbt-mode-hydra.el#L464-L490

**Comment by ag91** [comment]
Ah, that is just amazing!! Thanks for sharing that @VlachJosef. I shall mention that also in my post
then. I will close this then.
