### ISSUE TITLE
M-m on input line should go to first writable position

### ISSUE THREAD

**Issue by Trevoke** [hvesalai/emacs-sbt-mode#76]
Right now `M-m` goes to the very first character, which means that if I'm on the input line, I can't write instantly.

**Comment by fommil** [comment]
yeah, I noticed this one too recently, although I prefer `C-a`. Do you think you'd be able to fix it and send us a PR?

**Comment by Trevoke** [comment]
Hmm. Looks `C-a` is what does the right thing in other subshells.

I have no idea if I could fix it, since you don't have any tests I could use to help me avoid regressions. If I do give it a shot, do you have anything against `Cask` and `ecukes` for a test suite?

**Comment by fommil** [comment]
totally agree re: tests. We already have cask, just no tests. Look in .drone.yml for the CI commands. We use ecukes in ensime (not as much as I'd like)

**Comment by ashawley** [comment]
Looks like this has been broken since #36?  I'll work on a fix.

**Comment by ashawley** [comment]
Maybe it was broken after #72?  Still looking to fix, but I predict comint may not be well-suited for handling out-of-band output...

**Comment by hvesalai** [comment]
When doing a fix, also veryfy that you don't break https://github.com/ensime/emacs-sbt-mode/pull/93 as it may actually be realted to this. To test it, start a repl and then do a 

```
scala> Future{ while(true) { Thread.sleep(1000); println("output") } }
```

**Comment by hvesalai** [comment]
`C-A` is bound to `comint-bol`, which does the requested behavior.

M-m is bound to `back-to-indentation`

I propose the fix is just to remap `M-m` to the same as `C-A`
